# Generated by Django 4.2.4 on 2023-08-24 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voice_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('recipient_email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
