# Generated by Django 4.2.4 on 2023-08-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_bot', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freechatresponse',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_bot.freechat'),
        ),
    ]
