# Generated by Django 4.2.4 on 2023-08-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_bot', '0003_alter_freechatresponse_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreeChat',
            new_name='FreeChatSubject',
        ),
    ]
